### ISSUE TITLE
OAuth2 required

### ISSUE THREAD

**Issue by empierre** [davesteele/cloudprint-service#38]
Here is the message the package returns upon initiating login: 
https://developers.google.com/accounts/docs/AuthForInstalledApps

**Comment by davesteele** [comment]
Yes. Oauth2 support was added in version 0.11-7, released in May. The current version is 0.13-1 (0.14 is released upstream).

See other issue entries for things that may come up with your upgrade, In particular, cloudprint-service releases past 0.11-9 use systemd instead of sysv init, and cloudprint is upgraded to support a new incompatible release of the python-daemon module.

**Comment by empierre** [comment]
yes sorry, the debian packaged versions lies behind the github version visibly. 

I'll continue to test, thanks !
