### ISSUE TITLE
Question: Notifications not working?

### ISSUE THREAD

**Issue by mhoam** [davesteele/cloudprint-service#40]
Hi,
I have successfully installed the cloudprint service on a Raspberry 2 running Jessie (Debian 8) by setting up the PPA in my sources list as detailed here http://davesteele.github.io/cloudprint-service/ppa.html

When apt-get update and apt-get upgrade are used, cloudprint is "kept back" and not updated. As a result, the cloudprint package version is out of date (v0.11-9) The cloudprint-service package is up to date (V0.14-3). Systemctl shows that the service is started and running, and that the xmpp connection to google was established.

However, notifications of new print jobs do not appear to be working. 
When submitting a new job, it appears on the Google Cloud print management page as "queued". The cloudprint service is polling every hour, restarting the service results in the job being printed immediately.

Any guidance would be appreciated

**Comment by davesteele** [comment]
The "kept back" message indicates that cloudprint is a new dependency of cloudprint-service. It's not - that's a bug.

You can install things that are 'kept back' with 'apt-get dist-upgrade'. I do this regularly with wild abandon. Others [urge caution](http://askubuntu.com/questions/601/the-following-packages-have-been-kept-back-why-and-how-do-i-solve-it).

I don't know what the rest of your problem is, but I wouldn't dig deeper until the versions match.

Note that 0.14 has a different authentication model than 0.11-9. It will print a URL that you must visit with a graphical browser in order to complete the auth. See the [cps-auth](http://davesteele.github.io/cloudprint-service/man/cps-auth.html) man page.

**Comment by davesteele** [comment]
As it turns out, it's not a bug. The cloudprint upgrade requires the installation of a new package (likely config-argparse), and that triggers the 'kept back' logic.

That new package enables cloudprint [configuration files](https://github.com/davesteele/cloudprint-service/blob/master/debian/cloudprint.conf) in /etc/cloudprint.conf, and thus restores include/exclude/fastpoll functionality.

**Comment by mhoam** [comment]
Thanks for the prompt feedback. What would you suggest as to my next action?
Do I need to manually install the new package required or will a dist-upgrade identify and pick it up?

**Comment by davesteele** [comment]
apt-get dist-upgrade

**Comment by mhoam** [comment]
hi,
the dist-upgrade process added one new package "wiringpi" and upgraded one other "nuscratch", 
no sign of the "config-argparse" package.

dpkg-query for 'cloudprint*' shows the cloudprint package still at 0.11-9 and the cloudprint-service package at 0.14-3

When I re-try "apt-get install cloudprint", the following messages appear;
*The following packages have unmet dependencies:
 cloudprint : Depends: python-daemon (>= 2.0) but 1.5.5-1 is to be installed
              Depends: python-configargparse but it is not installable
E: Unable to correct problems, you have held broken packages.*

it looks like the package "python-configargparse" could be stopping the update, any idea why this is not installable?
thanks

**Comment by davesteele** [comment]
You are running into Debian bug [799227](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=799227), which is being addressed by [800163](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=800163).

I suspect that python-daemon is your real problem. If you don't want to wait for the stable update, you can try upgrading python-daemon on your own, then doing a forced install of cloudprint.

pip install -U python-daemon

**Comment by mhoam** [comment]
Just to be clear, Cloudprint can no longer be installed via the Debian 8 Jessie Repositories (on any platform?) until some unknown time in the future?
If this is the case then I suggest that the Cloudprint-Service PPA page on GitHub is amended to make this clear.
 
Thanks for your assistance

**Comment by davesteele** [comment]
*Cloudprint can no longer be installed via the Debian 8 Jessie Repositories (on any platform?)*

Correct

*until some unknown time in the future?*

I expect the fix to be in the next Debian stable update, projected for November.

*If this is the case then I suggest that the Cloudprint-Service PPA page on GitHub is amended to make this clear.*

I'll be deleting the PPA.
